version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: sentiment_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentiment_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
